image: maven:3.6.1-jdk-8

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/*.war

production:
  stage: deploy
  script:
  - apt-get update -yq
  - apt-get install rubygems ruby-dev -y
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
  - release
